version: "3"

services:
  db:
    build: ./db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=php_diary
      - MARIADB_USER=php_user
      - MARIADB_PASSWORD=php_password
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql

  web:
    image: php:8.2-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
