version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=diary
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/init:/docker-entrypoint-initdb.d

  php-apache:
    build: ./php # Använd den anpassade Dockerfile
    container_name: php-apache
    restart: always
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb
